### ISSUE TITLE
Revamp CI to use matrix builds with multiple OS's

### ISSUE THREAD

**Issue by lazar-mitrovic** [graalvm/native-build-tools#101]
ATM we are running tests only on Ubuntu 18.04 Linux. We should change that in order to have a complete test and regression coverage. See [docs](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
) for more information.

Fixing this issue depends on #100 and #102

**Comment by lazar-mitrovic** [comment]
Windows testing is blocked by https://github.com/gradle/native-platform/issues/274 and the following error for maven: https://github.com/graalvm/native-build-tools/blob/5e702c36415561a3e4057d9a94b485d889ff09c0/.github/workflows/test-native-maven-plugin.yml#L53

**Comment by dnestoro** [comment]
Currently we are testing on Windows and Linux
