### ISSUE TITLE
Question: How to run native tests that access directories in src/test/resources

### ISSUE THREAD

**Issue by srnagar** [graalvm/native-build-tools#110]
I am using `native-maven-plugin` version 0.9.1 and trying to run unit tests that access files in `src/test/resources/<sessiondir>/<resourcefiles>`.  

Tests run successfully in the standard JVM `test` task but when running as native tests, they fail because the `<resourcefiles>` are not found. I tried adding the test resource directory (`sessiondir`) in `resource-config.json` but it didn't work.

How do I include these resources for native testing?

**Comment by graemerocher** [comment]
Resource config inference coming in 0.9.3 might help here https://github.com/graalvm/native-build-tools/pull/83

**Comment by lazar-mitrovic** [comment]
I believe that [using `native-image-agent`](https://github.com/graalvm/native-build-tools/blob/master/native-gradle-plugin/README.md#reflection-support) will fix your issue.

**Comment by lazar-mitrovic** [comment]
Does previous comment work for you @srnagar ?

**Comment by srnagar** [comment]
@lazar-mitrovic I haven't had a chance to try this out but I'll try it out this week and let you know. Thanks for the guidance!
