### ISSUE TITLE
nativeBuild gradle failing at 'generateTestAot' task

### ISSUE THREAD

**Issue by anumalasri** [graalvm/native-build-tools#111]
Hi,

gradle nativeBuild failing at 'generateTestAot' task

```
Execution failed for task ':generateTestAot'.
> 'org.springframework.asm.AnnotationVisitor org.springframework.core.type.classreading.MergedAnnotationReadingVisitor.get(java.lang.ClassLoader, java.util.function.Supplier, java.lang.String, boolean, java.util.function.Consumer)'
```

I am using below Gradle & Java version as shown below with Spring Boot 2.5.3 and Native Gradle Plugin v0.9.2

Not able to find what's wrong with build.  Can you able to help how to fix this error ?    
 

```
------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (GraalVM Community 11.0.11+8-jvmci-21.1-b05)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by sbrannen** [comment]
The error you encountered is not related to the `native-build-tools` project.

Rather, it is due to a change in Spring Framework 5.3.9.

The Spring AOT support was updated to account for this change in https://github.com/spring-projects-experimental/spring-native/commit/efaee32d9557040aee9f061ce4da3d6d80df82c9#diff-d4534ef3a1a8ce16ac634ac6f2c621213ca4f8b981bfe7af83f757cf57064d06L72.

You will therefore need to wait for the next `spring-native` release that includes the above update or downgrade to Spring Framework 5.3.8 in the interim.

**Comment by anumalasri** [comment]
@sbrannen ..  Thanks for details and pointing out spring framework version changes.   Let me check more about versions in my project and see if any adjustments required. 

However, the error from `native-build-tools` is not sufficient to find actual problem like version conflicts.  
Please consider to improve error messages as native-image builds are still evolving and would be helpful to users.

**Comment by sbrannen** [comment]
> However, the error from `native-build-tools` is not sufficient to find actual problem like version conflicts.
> Please consider to improve error messages as native-image builds are still evolving and would be helpful to users.

The `generateTestAot` Gradle task is not part of the `native-build-tools` project. So the `native-build-tools` project cannot improve the error message.

If you would like to see better error messages for the `generateTestAot` Gradle task, please raise an issue against the [`spring-native`](https://github.com/spring-projects-experimental/spring-native/issues/new) project.
