### ISSUE TITLE
Add agent support to the Maven plugin

### ISSUE THREAD

**Issue by sdeleuze** [graalvm/native-build-tools#13]
For both building and testing support, see related `agent` and `persistConfig` Gradle plugin properties.

**Comment by michael-simons** [comment]
Yes please. I see a lot of potential to solve reflection based issues in assertions via AssertJ `extract` and possibly others, which will only be a problem in test code.

In addition it would cater for JUnit constructs that require reflection, without the user having to cater for them.

**Comment by sbrannen** [comment]
> In addition it would cater for JUnit constructs that require reflection, without the user having to cater for them.

See related discussion in https://github.com/graalvm/native-build-tools/issues/50#issuecomment-862186948.
