### ISSUE TITLE
The Maven plugin README shows Gradle-related code

### ISSUE THREAD

**Issue by nfrankel** [graalvm/native-build-tools#130]
>## Building
>This plugin follows standard maven plugin conventions and as such can be built as:
>
>```shell
>./gradlew publishAllPublicationsToCommonRepository
>```
>
> -- https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/README.md

Comes from [this change](https://github.com/graalvm/native-build-tools/commit/c2e3b24246ce23bd2a0fbf71fb7f6e652adf2662).

 I know @melix hates Maven, but I assume it was not done on purpose 😂😂😂

**Comment by melix** [comment]
This isn't a mistake: the Maven plugin is built with Gradle ;)

**Comment by nfrankel** [comment]
Wow! That's an interesting approach. Thanks for the feedback

**Comment by melix** [comment]
There are different reasons for this:

- this project is a multi-project build with common code between the Gradle and Maven plugins and this setup allows consistent build without hassle (changing the common module would automatically trigger rebuild of downstream plugins without having to publish anything to a local repo)
- isolation of functional tests (avoiding pollution of .m2 in particular)
- performance/caching
- each project can still be built in isolation without breaking integration

More details on https://github.com/graalvm/native-build-tools/pull/87 and https://github.com/graalvm/native-build-tools/pull/103

**Comment by nfrankel** [comment]
No worries, this isn't a documentation regression, that's the main point.
