### ISSUE TITLE
Support junit3 test framework

### ISSUE THREAD

**Issue by lusou-zhangquan** [graalvm/native-build-tools#135]
When we are testing BouncyCastle java project (https://github.com/bcgit/bc-java) based on this native build tool, we found that test cases were not compiled and tested as expected with `gradle nativeTest` command. The reason is that the test cases of this project is based on junit3, while this plugin support junit4+ only. Therefore, we did some work on the basis of this tool to enable test cases based on junit3 framework, and now test cases in BouncyCastle could be built and run automatically. There are many java projects whose test cases are based on junit3 and developers want to test them with this native build tool. Finally, we are glad to contribute this feature to this project if it could be accepted.

**Comment by lusou-zhangquan** [comment]
Thanks for your patient explanation firstly.

As mentioned above, I have tried to run junit3 test cases using this plugin but none was executed.
In my understanding, this plugin works like this:
1. Collect class and method information during executed in jvm mode;
2. Export to config file whose name starts with `junit-platform-unique-ids`;
3. Enable `JUnitPlatformFeature` during graal native image building;
4. Register classes parsed from config file and add them to `testPlan` of `DefaultLauncher`;
5. Launch it and finish test;
Please point it out directly if there is anything incorrect.

And we think the reason that junit3 test cases was not executed is:
1. Test cases base on junit3 are not registered because they are not found in config file exported during jvm execution;
2. `junit-vintage-engine` supports junit3 but its entry `VintageTestEngine` was not enabled in this plugin;

And we tried to fix them by:
1. Enable newly-added `JUnit3PlatformFeature` during graal native image building which collect and register junit3 test cases;
2. Enable `VintageTestEngine` or original `TestRunner` to start junit3 test.

Hope for your better advices. Thanks!

**Comment by lazar-mitrovic** [comment]
Have you managed to run your project using `junit-platform` dependency in JVM mode?

As far as I see, you are still using
```
testCompile group: 'junit', name: 'junit', version: '4.11'
```
and that won't work, and will not be supported. You'll need to [migrate to `junit-platform`](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-running) in order for listener to pick up your tests. You also might need to configure `junit-vintage-engine`. See [this project](https://github.com/junit-team/junit5-samples/tree/main/junit5-migration-gradle) as an example of proper migration to JUnit Platform.

**Comment by lusou-zhangquan** [comment]
Thanks for your suggestions and I've tried them. But I find that it works for simple junit3 test cases but still not work for BouncyCastle project. Here is the build.gradle cofiguration
```
test {
	useJUnitPlatform {
		includeEngines("junit-vintage")
	}
}
dependencies {
	testImplementation("junit:junit:4.13.2")
	testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.8.2")
}
```
With https://github.com/graalvm/native-build-tools/pull/187, BouncyCastle test cases could work properly at present.

**Comment by lazar-mitrovic** [comment]
I believe that JUnit3 tests not working in `junit-vintage` engine should be filed as upstream JUnit bug (cc @sbrannen).

**Comment by sbrannen** [comment]
> I believe that JUnit3 tests not working in `junit-vintage` engine should be filed as upstream JUnit bug (cc @sbrannen).

Yes. @lusou-zhangquan, if you have discovered JUnit 3.8 based test cases that are not supported by the JUnit Vintage test engine, please report them to [JUnit 5](https://github.com/junit-team/junit5/issues/new/choose).
