### ISSUE TITLE
Create a "current" or "latest" link for the latest version of the docs

### ISSUE THREAD

**Issue by ilopmar** [graalvm/native-build-tools#160]
It would be good if there is a "current" or "latest" alias of the documentation so we can link them without setting a specific version.

We have in our Micronaut Gradle plugin links to 0.9.6 but there is a now a 0.9.7.1. It is error prone and a time consuming task to remember to update the docs every time there is a new version. 

So, besides publishing to:
```
https://graalvm.github.io/native-build-tools/0.9.6/gradle-plugin.html#changelog
```

It would be good to also have:

```
https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#changelog
```

**Comment by melix** [comment]
There's a redirect for the latest version: https://graalvm.github.io/native-build-tools

However there's no redirect link for the Maven or Gradle plugin, only for the landing page.

**Comment by ilopmar** [comment]
I think it's worth it to add the redirect also for the plugins. I think that tools using the plugin will want to link specific sections of the plugins, no the main page for the native-build-tools

**Comment by lazar-mitrovic** [comment]
We could create a simple symlink as they [work with Github Pages](https://github.com/chetabahana/symlink).

**Comment by melix** [comment]
Oh, didn't know that!

**Comment by melix** [comment]
This now done. thanks for the suggestion about the symlink, makes things much easier!

**Comment by ilopmar** [comment]
Awesome! :tada:
