### ISSUE TITLE
Introduce `skipNativeTests` in Maven plugin

### ISSUE THREAD

**Issue by sbrannen** [graalvm/native-build-tools#179]
## Overview

`NativeBuildMojo` has a `skipNativeBuild` property.

Whereas, `NativeTestMojo` has a `skipTests` property.

This means that you can skip the tests, but that skips the JVM tests **and** the native tests, since Maven Surefire looks for the same [`skipTests` property](https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html).

Some workflows have the need to execute tests on the JVM using the `agent` in order to generate native configuration files but don't have the need to execute the tests within a native image.

We should therefore support such use cases via a command line similar to the following.

```shell
mvn -Pnative -Dagent=true -DskipNativeTests test
```

## Deliverables

- [x] Introduce a `skipNativeTests` property to skip only the native tests.

**Comment by sbrannen** [comment]
As an alternative, it might be better to replace `skipTests` in `NativeTestMojo` with `skipNativeTests`.

`skipTests` would then only apply to Maven Surefire; whereas, `skipNativeTests` would only apply to the Native Build Tools.

**Comment by sdeleuze** [comment]
I tend to think that `skipTests` should still aply on both Surefire and NBT because:
 - Without JVM tests we can't run native test due to missing test ids
 - In term of semantics, it makes sense from POV to skip both
 
So this issue should be only about adding `skipNativeTests` without changing `skipTests` behavior.

**Comment by sbrannen** [comment]
> So this issue should be only about adding `skipNativeTests` without changing `skipTests` behavior.

We could certainly do it like that for now and change it later if we desire (see below).

> Without JVM tests we can't run native test due to missing test ids

That's currently true, but if #76 gets implemented that would no longer be the case.

**Comment by sbrannen** [comment]
PR #193 is ready for review.
