### ISSUE TITLE
Native plugin fails if no tests are run in a module

### ISSUE THREAD

**Issue by dzou** [graalvm/native-build-tools#188]
The native-maven-plugin will fail if no tests are run for some module after running `mvn test -Pnative`. It fails with the error "Test configuration file wasn't found. Make sure that test execution wasn't skipped." (No test config file will be written if no tests are run)

Error:
```
[ERROR] Test configuration file wasn't found. Make sure that test execution wasn't skipped.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for native-junit-experiment 1.0-SNAPSHOT:
[INFO] 
[INFO] native-junit-experiment ............................ SUCCESS [  0.051 s]
[INFO] empty-test-module .................................. FAILURE [  0.544 s]
[INFO] simple-module ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.860 s
[INFO] Finished at: 2022-01-06T10:09:52-05:00
```

Repro: https://github.com/dzou/native-plugin-empty-tests

I would expect the tests to just pass if no tests are run. This is important for multi-module projects because we use a test-filter which only runs native-image integration tests, and in multi-module projects, not all modules have native-image tests. It would then be useful in these cases to have the tests to pass if there's no tests that are run for some module.

**Comment by mpeddada1** [comment]
Hi @sbrannen, thanks again for a great product! Just checking in, do we have any updates on this issue?

**Comment by alvarosanchez** [comment]
@sbrannen I have taken a look at this. The problem in the reproducing example is that `empty-test-module` comes before `simple-module`. The latter do have tests, but we are halting the execution prematurely in the former.

I find it more appropriate to just warn about it and let the reactor execution continue. What do you think?

**Comment by lazar-mitrovic** [comment]
Applicable to Gradle as well:
```
> Task :nativeTestCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':nativeTestCompile' (type 'BuildNativeImageTask').
  - In plugin 'org.graalvm.buildtools.gradle.NativeImagePlugin$Inject' type 'org.graalvm.buildtools.gradle.tasks.BuildNativeImageTask' property 'testListDirectory' specifies directory 'native-plugin-empty-tests/empty-test-module/build/test-results/test/testlist' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the directory exists before the task is called.
      2. Make sure that the task which produces the directory is declared as an input.
    
    Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
```

**Comment by sbrannen** [comment]
> I find it more appropriate to just warn about it and let the reactor execution continue. What do you think?

Yes, just warning about the situation would be better.

In any case, a multi-module/project build (Maven or Gradle) should not fail if some of the modules/projects don't have tests.
