### ISSUE TITLE
Cannot configure "trace-output" agent option because plugins add "config-output-dir" option by default

### ISSUE THREAD

**Issue by hannesd** [graalvm/native-build-tools#189]
Using the following in the maven plugin's &lt;configuration> section:

```xml
                            <agent>
                                <options>
                                    <option>trace-output=${basedir}/trace-output.json</option>
                                </options>
                            </agent>
```
 causes `mvn test` to fail with the following message:

```
native-image-agent: can only once specify exactly one of trace-output=, config-output-dir= or config-merge-dir=.
```

Looking at the sources of the maven plugin it appears that the plugin explicitly forbids adding the `config-output-dir` but also does not allow me to remove it. I suggest to allow overriding the `config-output-dir` option by the user and not adding the `config-output-dir` option by default when one of the other options is present.

**Comment by sbrannen** [comment]
If a change along these lines is made to the Maven plugin, the same will have to be done for the Gradle plugin as well.

**Comment by sbrannen** [comment]
> Looking at the sources of the maven plugin it appears that the plugin explicitly forbids adding the `config-output-dir`

That's correct. The reason this is done is to ensure that the plugin also knows the location it needs to read the generated configuration files.

> but also does not allow me to remove it. I suggest to allow overriding the `config-output-dir` option by the user and not adding the `config-output-dir` option by default when one of the other options is present.

If the `config-output-dir` is removed (and therefore no longer under the control of the plugin), the plugin will not be able to automatically use the generated configuration files when building the native image.

So, if we allow the `config-output-dir` to be overridden or disabled, we either need to log a warning or info message to inform the user about this, or we need to make sure there's an easy way to tell the plugin where to look for the generated configuration files when building the native image.

**Comment by hannesd** [comment]
Thanks for the insights!

> So, if we allow the config-output-dir to be overridden or disabled, we either need to log a warning or info message to inform the user about this, or we need to make sure there's an easy way to tell the plugin where to look for the generated configuration files when building the native image.

From your answer I'll take it you'd be willing to accept a pull request if the issue is resolved as described by you? If so I will look into it this evening and if successful update my PR (+ sign CA). I'd prefer to let the plugins know where the configuration can be found instead of a warning but I have to dive deeper into the code to tell whether that approach is practical.

I wonder what should happen when the user wants a trace instead of the config. No point in letting the plugins know where the configuration is, when no configuration is produced (native-image produces either one or the other but not both, if I'm not mistaken). Maybe things become clearer after I've looked at the code some more.

**Comment by lazar-mitrovic** [comment]
I believe #230 fixed this by changing the way we are configuring agent.
