### ISSUE TITLE
System Properties specified in maven-surefire-plugin not available at run-time

### ISSUE THREAD

**Issue by mpeddada1** [graalvm/native-build-tools#196]
Hi all, thank you for this great project!

We’re trying to run tests using System Properties defined in the maven-surefire-plugin but it looks like these properties are not getting recognized during run time. 

Here is a reproducer this issue:  https://github.com/mpeddada1/native-image-system-properties. 

Running `mvn test -P native` at the root of the project results in the System property being null, as shown below:
 
```
[INFO] Executing: ../projects/native-image-experiments/native-image-system-properties/child-project/target/native-tests --xml-output-dir ..projects/native-image-experiments/native-image-system-properties/child-project/target/native-test-reports
JUnit Platform on Native Image - report
----------------------------------------

com.example.SimpleTest > simpleTest FAILED


Failures (1):
  JUnit Vintage:SimpleTest:simpleTest
    MethodSource [className = 'com.example.SimpleTest', methodName = 'simpleTest', methodParameterTypes = '']
    => expected: hello
but was : null
       com.google.common.truth.FailureMetadata.fail(FailureMetadata.java:192)
       com.google.common.truth.Subject.doFail(Subject.java:1186)
       com.google.common.truth.Subject.failEqualityCheckNoComparisonFailure(Subject.java:986)
       com.google.common.truth.Subject.failEqualityCheck(Subject.java:865)
       com.google.common.truth.Subject.standardIsEqualTo(Subject.java:175)
       com.google.common.truth.Subject.isEqualTo(Subject.java:169)
       com.example.SimpleTest.simpleTest(SimpleTest.java:16)
       java.lang.reflect.Method.invoke(Method.java:566)
       [[Testing framework: 30 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
       org.graalvm.junit.platform.NativeImageJUnitLauncher.execute(NativeImageJUnitLauncher.java:74)
       [...]

```

According to the [documentation on system properties and GraalVM](https://www.graalvm.org/22.0/reference-manual/native-image/Properties/), the system properties need to be provided at run-time. However, it looks the command created by the native maven plugin to run the executable does not include them.

Is there a way to pass in extra arguments to the command created by the plugin or a workaround to bake the properties into the native image?

**Comment by lazar-mitrovic** [comment]
We have this option on Gradle plugin:
```groovy
            // Runtime options
            runtimeArgs.add('--help') // Passes '--help' to built image, during "nativeRun" task
```
but it seems to be missing on Maven side.

**Comment by mpeddada1** [comment]
Thank you for your response and the background info @lazar-mitrovic! We were able get a workaround for this by initializing the class that uses the extra arguments at build-time.
