### ISSUE TITLE
Document that Gradle plugin requires `java-library` or `application` plugins to be set

### ISSUE THREAD

**Issue by sergey-morenets** [graalvm/native-build-tools#210]
Hi

I tried to use Gradle plugin as mentioned in the documentation: https://graalvm.github.io/native-build-tools/0.9.10/gradle-plugin.html

build.gradle.kts:

```
plugins {
   id("org.graalvm.buildtools.native") version "0.9.9"
}
```

settings.gradle.kts:

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```

However when I try to run native build: **gradle nativeCompile** I get the error message:

`Task 'nativeCompile' not found in root project`

and **gradle tasks** command doesn't print any tasks related to the native-image plugin.

**Comment by melix** [comment]
The plugin won't do anything by itself if you don't have either the `java-library` (for libraries) or `application` (for applications) plugin applied: it works _in addition_ to your regular Java plugins.

**Comment by sergey-morenets** [comment]
Thank you, @melix 

I already discovered that by looking at the samples. So this configuration in build.gradle.kts worked for me:

```
plugins {
   id("application")
   id("org.graalvm.buildtools.native") version "0.9.9"
}

```

But I guess it would be nice to add few words about java-library/application in the documentation.

**Comment by melix** [comment]
Agreed.
