### ISSUE TITLE
NativeImagePlugin configures wrong test results dir

### ISSUE THREAD

**Issue by oehme** [graalvm/native-build-tools#218]
https://github.com/graalvm/native-build-tools/blob/4f02438a5da9e30d4352dc18c966bf789caf9486/native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java#L384

This makes the global test results dir an output, which means it will overlap with every other `Test` task in the project, preventing caching.

**Comment by melix** [comment]
Oh good catch, it should have been the test list file instead.
