### ISSUE TITLE
Plugin fails to execute nativeBuild task on Windows ()

### ISSUE THREAD

**Issue by miho** [graalvm/native-build-tools#232]
**Describe the bug**

- os:
- plugin id: `id 'org.graalvm.buildtools.native' version '0.9.11'`
- graalvm: 

The plugin fails to execute the `nativeBuild ` task and fails with

    Fatal error: Unsupported OptionOrigin: C:\Users\devuser\AppData\Local\Temp\native-image4967625859144225621args

**To Reproduce**

```pwsh
./gradlew clean assemble nativeBuild 
```

**Expected behavior**

The task should complete without errors.

**System Info (please complete the following information):**
 - OS:  `windows 10 x86_64`
 - GraalVM Version: `22.1.x`
 - Java Version: `17`
 - Plugin version: `native-gradle-plugin:0.9.11`

**Additional context**

**Comment by lost4git** [comment]
update to version graalvm-nightly-jdk17@22.2.0-dev-20220513_2122 can resolve it

**Comment by alvarosanchez** [comment]
Another option is to not use the args file, and use the old mechanism to avoid long classpath issue on Windows, described here: https://graalvm.github.io/native-build-tools/0.9.9/maven-plugin.html#long_classpath_and_shading_support

With 0.9.11+ and GraalVM 22.1.0, this would be something like the following:

```xml
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>${native.maven.plugin.version}</version>
    <extensions>true</extensions>
    <executions>
        <execution>
            <id>build-native</id>
            <goals>
                <goal>build</goal>
            </goals>
            <phase>package</phase>
        </execution>
    </executions>
    <configuration>
        <skip>false</skip>
        <useArgFile>false</useArgFile>
        <imageName>${imageName}</imageName>
        <buildArgs>
            <buildArg>--no-fallback</buildArg>
        </buildArgs>
        <classpath>
            <param>${project.build.directory}/${project.artifactId}-${project.version}-shaded.jar</param>
        </classpath>
    </configuration>
</plugin>
```

**Comment by chirontt** [comment]
@alvarosanchez thanks a lot for the tip about the "useArgFile" configuration parameter; this parameter works around the problem of `Unsupported OptionOrigin` in Windows, and it works for both Gradle and Maven native build tools plugins, to boot.

**Comment by mstine** [comment]
FWIW, the old shading mechanism doesn't work with Spring, which was one of the motivators for args file support. Any word on when we'll see a proper fix?

**Comment by lazar-mitrovic** [comment]
> FWIW, the old shading mechanism doesn't work with Spring, which was one of the motivators for args file support. Any word on when we'll see a proper fix?

This issue was fixed in GraalVM (see https://github.com/oracle/graal/pull/4561) so it will land in upcoming release (22.2).
Only workaround that we could implement until then would be to move `argFile` location to a relative directory (perhaps `build/tmp/native-image4967625859144225621args`) but I'm not sure if that is good idea, WDYT @melix?

**Comment by mstine** [comment]
> > FWIW, the old shading mechanism doesn't work with Spring, which was one of the motivators for args file support. Any word on when we'll see a proper fix?
> 
> This issue was fixed in GraalVM (see [oracle/graal#4561](https://github.com/oracle/graal/pull/4561)), so it will land in the upcoming release (22.2). Only workaround that we could implement until then would be to move `argFile` location to a relative directory (perhaps `build/tmp/native-image4967625859144225621args`) but I'm not sure if that is good idea, WDYT @melix?

Thanks - what's the best way to understand the timeline for GraalVM releases?

**Comment by lazar-mitrovic** [comment]
> > > FWIW, the old shading mechanism doesn't work with Spring, which was one of the motivators for args file support. Any word on when we'll see a proper fix?
> > 
> > 
> > This issue was fixed in GraalVM (see [oracle/graal#4561](https://github.com/oracle/graal/pull/4561)), so it will land in the upcoming release (22.2). Only workaround that we could implement until then would be to move `argFile` location to a relative directory (perhaps `build/tmp/native-image4967625859144225621args`) but I'm not sure if that is good idea, WDYT @melix?
> 
> Thanks - what's the best way to understand the timeline for GraalVM releases?

Version roadmap is hosted here: https://www.graalvm.org/release-notes/version-roadmap/
You can try nightly versions from here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Comment by zingermax** [comment]
> @alvarosanchez thanks a lot for the tip about the "useArgFile" configuration parameter; this parameter works around the problem of `Unsupported OptionOrigin` in Windows, and it works for both Gradle and Maven native build tools plugins, to boot.

setting  <skip>false</skip> causing build task to fail with message :
" The command line is too long."

**Comment by miho** [comment]
With 22.2 being released, the issue has been solved for me. Thanks for looking into it.
