### ISSUE TITLE
[QUESTION] how to set the gradle agent DSL Flag?

### ISSUE THREAD

**Issue by alexanderankin** [graalvm/native-build-tools#246]
**Describe the problem**
I am trying to automate the running of the tracing agent task in order that my native image task can generate a usable image without any manual copying steps.

**Make sure that you have read [the documentation](https://graalvm.github.io/native-build-tools) and that you are using the latest plugin version.**
I am referring to [https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support) and I am seeing a reference to a DSL flag:

> The agent can also be enabled by setting the corresponding DSL flag; however, that is not recommended since this is a development mode feature only.

but I cannot tell what this flag looks like in groovy code. E.g. I can run `./gradlew -Pagent test` successfully, but how can i run `./gradlew customTask` where customTask turns on the agent using the dsl instead of a `-P` cli argument.

**Additional context**
basically, i have the following going on in my `build.gradle`:

<details><summary>build.gradle contents</summary>

```gradle
import org.graalvm.buildtools.gradle.tasks.BuildNativeImageTask

plugins {
    id 'project.specific.app-conventions' // shadow, lombok, native-build-tools, etc...
}

version = '0.0.1'

dependencies {
    annotationProcessor 'info.picocli:picocli-codegen:4.6.3'
    implementation 'org.eclipse.jgit:org.eclipse.jgit:6.1.0.202203080745-r' // they are not huge graalvm fans, this is what i need to trace
    implementation 'info.picocli:picocli:4.6.3'
    implementation 'ch.qos.logback:logback-classic:1.2.11'
}

application {
    mainClass.set 'package.SomeClass'
}

jar {
    from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }) {
        exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
    }
    manifest {
        attributes('Main-Class': 'package.SomeClass')
    }
}

shadowJar { // todo make it depend on traceIt
    archiveBaseName.set 'shadow'
}

/*
  what im trying to do here is to emulate "./gradlew -Pagent test" from the docs - https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support

  needless to say it doesn't work
*/
tasks.register('traceIt') {
    doFirst {
        System.setProperty('agent', 'true')
    }
    finalizedBy tasks.test
}

// really verbose and manual way of running with tracing agent, works
// makes you question if you're doing it right or not
// this is not running a test suite, i did implement a test suite that does in src/test/java
tasks.register('traceIt', JavaExec) {
    group 'build'
    description 'build graalvm config by running with agent'
    classpath sourceSets.main.runtimeClasspath
    mainClass = 'package.SomeClass'

    // test data
    def repo = 'https://github.com/msangel/promisified-resource-loader'
    args '-r', repo, '-b', 'master'

    it.jvmArgs += ('-agentlib:native-image-agent=config-output-dir=' +
            project.buildDir.toPath().resolve('native/agent-output/test')) // todo add to main sourceSet
}

// https://graalvm.github.io/native-build-tools/0.9.11/gradle-plugin.html#_configuration_options
graalvmNative {
    binaries {
        main {
            // Main options
            imageName.set project.name
            mainClass.set application.mainClass.get()

            debug.set false
            verbose.set true
            fallback.set false
            buildArgs.add('-Ob') // faster development builds
            // https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/URLProtocols.md
            buildArgs.add('--enable-http')
            buildArgs.add('--enable-https')
            // useFatJar.set true
        }
    }
}

tasks.named('nativeCompile', BuildNativeImageTask) {
    dependsOn tasks.shadowJar
    classpathJar = tasks.shadowJar.outputs.files.singleFile
}

```

</details>

**System Info (please complete the following information):**
 - OS: [e.g. `Windows`] ubuntu 20.04
 - GraalVM Version [e.g. `22.0 CE`] 22.1.0 CE
 - Java Version [e.g. `17`] 17
 - Plugin version [e.g. `native-gradle-plugin:0.9.10`] 9.11

**To Reproduce**
If possible please attach a complete reproducer here (either as [a zip file](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to public repository/branch).

**Comment by alexanderankin** [comment]
the replacement code in my additional context works btw, the question is more about the documentation -- i even took a look at the source code and its not obvious to me where the programmatic flag is that replace `-Pagent`

**Comment by lazar-mitrovic** [comment]
Up until `0.9.12` release DSL option for this flag was:
```
            // Development options
            agent {
                enabled = true // Enables the reflection agent. Can be also set on command line using '-Pagent'
            }
```
See [the docs](https://graalvm.github.io/native-build-tools/0.9.11/gradle-plugin.html#_configuration_options) for more info.

However, in 0.9.12 we completely reworked [how the agent configuration works](https://graalvm.github.io/native-build-tools/0.9.12/gradle-plugin.html#agent-support), so now it is required to manually specify `-Pagent` and persist the metadata in the code base using `metadataCopy` task, as agent run is intended to be a one-off thing.
