### ISSUE TITLE
[QUESTION] Gradle Plugin has `junit-jupiter` in runtime

### ISSUE THREAD

**Issue by jvmusin** [graalvm/native-build-tools#250]
Hi. The gradle build plugin has an implementation (not test one) dependency on `junit-jupiter` in utils project: https://github.com/graalvm/native-build-tools/blob/a9b5900e4f333294281e1444931febfb8a1cc261/common/utils/build.gradle.kts#L54

Was this made intentionally? If so, why?
I want to reuse your plugin by applying your plugin transitively inside my own plugin and it's strange to see `junit-jupiter` during dependencies resolution stage.

**Comment by melix** [comment]
You are absolutely right, those should be test dependencies!
