### ISSUE TITLE
Remove deprecated Gradle features

### ISSUE THREAD

**Issue by lazar-mitrovic** [graalvm/native-build-tools#262]
ATM there is a lot of `forUseAtConfigurationTime`, `JavaPluginConvention` etc. scattered throughout Native Gradle Plugin.
We should get rid of them before the Gradle 8.0 release (whenever that might be).

**Comment by sschuberth** [comment]
> before the Gradle 8.0 release (whenever that might be).

FYI, there's https://docs.gradle.org/8.0-rc-1/release-notes.html by now.

**Comment by melix** [comment]
Was done as part of 0.9.21
