### ISSUE TITLE
Introduce flags to activate native debugging and quick build

### ISSUE THREAD

**Issue by graemerocher** [graalvm/native-build-tools#267]
Currently there is no easy way to access super common functionality like activating native image debugging and quick builds.

This proposal is to extend the build tooling for both Gradle and Maven to surface this functionality without having to resort to build configuration.

This is also critical for the long term integration of the build tooling into IDEs but mostly importantly developers can develop muscle memory and assign aliases to access this functionality without having to dive into `build.gradle` or `pom.xml`

## Gradle Proposal

```
gradle nativeTest --quick-build-native
gradle nativeTest --debug-native
```

## Maven Proposal

Less sure about these (ideas welcome):

```
mvn test -Pnative -DquickBuild
mvn test -Pnative -DdebugNative
```

**Comment by alvarosanchez** [comment]
In the case of Maven, the flags already exist:

```
mvn test -Pnative -DquickBuild
mvn test -Pnative -Ddebug #native-image -g
```

**Comment by melix** [comment]
For the record, this is how a _task_ can override a property based on a CLI option:

```
    @Input
    abstract Property<Boolean> getFlag()

    @Option(option = "flag", description="Some flag")
    void overrideFlag() {
        getFlag().set(true)
    }


```

this would let the user invoke with `--flag`, which would set the value of the `flag` property, overriding whatever is used in the DSL.

**Comment by graemerocher** [comment]
> In the case of Maven, the flags already exist:
> 
> ```
> mvn test -Pnative -DquickBuild
> mvn test -Pnative -Ddebug #native-image -g
> ```

In that case the task is to implement the same for Gradle
