### ISSUE TITLE
Unable to customize the metadataRepository URI with Gradle

### ISSUE THREAD

**Issue by sdeleuze** [graalvm/native-build-tools#282]
I tried various way of customizing the metadataRepository URI with Gradle like `uri(file("metadata-repository"))` [as documented](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#_enabling_the_metadata_repository) (with a file or a directory) but I was not able to make it working.

When debugging, in `GraalVMReachabilityMetadataService` customization of the version are taken in account, not the uri ones.

**Comment by sdeleuze** [comment]
For some reason in `NativeImagePlugin` [here](https://github.com/graalvm/native-build-tools/blob/45a516ea4e10765c530679bbc195c58642c25d0d/native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java#L318) the value returned by `repositoryExtension.getUri()` is always the default one, regardless of any customization made to the uri.

**Comment by lazar-mitrovic** [comment]
I tried the following with the current SNAPSHOT:
- ``` git clone git@github.com:oracle/graalvm-reachability-metadata.git ```
- Add the following to the `build.gradle`
  ```groovy
  graalvmNative {
      metadataRepository {
          enabled = true
          uri(file('/home/xxxxx/graalvm-reachability-metadata/metadata'))
      }
      binaries.all {
    	  verbose = true
      }
  }
  
  dependencies {
      implementation 'org.postgresql:postgresql:42.3.4'
  }
  ```
- Run `gradle nativeCompile` and the output will contain:
  ```
  -H:ConfigurationFileDirectories=/home/xxxxx/debug/build/native/generated/generateResourcesConfigFile,/home/xxxxx/graalvm-reachability-metadata/metadata/org.postgresql/postgresql/42.3.4 \
  ```

Could you share a reproducer?

**Comment by sdeleuze** [comment]
Hum, I can't, not sure why, sorry for the noise.

**Comment by sdeleuze** [comment]
It was probably due to the fact we configure Gradle plugin programmatically in https://github.com/spring-projects/spring-aot-smoke-tests so nothing related to NBT.
