### ISSUE TITLE
Failing to build project using gradle - Task: Javadoc Failed

### ISSUE THREAD

**Issue by mfranklin1** [graalvm/native-build-tools#284]
I'm attempting to build the master branch to obtain a copy of native-maven-plugin:0.9.14-SNAPSHOT as I keep getting an error when using 0.9.13 due to a null pointer exception which is fixed in this snapshot. I cannot use the plugin until I track down the issue with my build and for that I need to use the latest snapshot version which I apparently cannot download from the rawgithubcontents web site and I cannot find any other location. So I'm forced to attempt to build the plugin myself.

However when I attempt to build the plugin using 

./gradlew publishAllPublicationsToCommonRepository

I get 

> Task :javadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/mnt/c/github/native-build-tools/native-maven-plugin/build/tmp/javadoc/javadoc.options'

My environment - ubuntu 20.04 running on windows wsl 2

mvn -v
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/maven
Java version: 17.0.4, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.102.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

gradle -v

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.17
Ant:          Apache Ant(TM) version 1.10.7 compiled on October 24 2019
JVM:          17.0.4 (Private Build 17.0.4+8-Ubuntu-120.04)
OS:           Linux 5.10.102.1-microsoft-standard-WSL2 amd64

I've also tried gradle 7.5.1 and java 11 

Just pulling master branch to local machine and attempting to build.

Is there any documentation on exactly what environment I can use to build this in? A docker image maybe?

Or can I just get a copy of the latest 0.9.14-snapshot plugin so I can find my bug without the nullpointerexception?

**Comment by lazar-mitrovic** [comment]
Hi, can you send me the output of 
```
./gradlew publishToMavenLocal --no-parallel --stacktrace
```

**Comment by mfranklin1** [comment]
So kind of weird - I'm using openjdk17, but I have an install of openjdk11 on the box which doesn't have javadoc in the bin directory - no idea why. Anyway JAVA_HOME is set to openjdk17 and don't see any other env vars pointing at openjdk11, but gradle was using the path to the missing javadoc for some reason - it's using java 17 for the build though. So I rebooted the machine and now ./gradlew --no-parallel --stacktrace publishToMavenLocal and ./gradlew publishAllPublicationsToCommonRepository work. Please close this - looks like installing the jdk was at fault. Thanks.
