### ISSUE TITLE
nativeCompile and nativeRun always rebuild the image

### ISSUE THREAD

**Issue by graemerocher** [graalvm/native-build-tools#285]
**Describe the bug**

When using nativeCompile and nativeRun a native executable is always built even if nothing has changed, it seems the inputs and outputs are not correctly configured?

**To Reproduce**

Run `./gradlew nativeCompile` twice

**Expected behavior**

If nothing has changed a native executable shoudn't be rebuilt.

**System Info (please complete the following information):**
 - OS: Mac
 - GraalVM Version 22.2
 - Java Version 17
 - Plugin version Micronaut plugin 3.5.1 (I assume the latest?)

**Comment by lazar-mitrovic** [comment]
I'm trying the `java-application` sample at the moment with the current SNAPSHOT and it works fine. 
Would you mind sharing a reproducer?
