### ISSUE TITLE
Add link to sample to the Maven and Gradle Documentation pages

### ISSUE THREAD

**Issue by krisfoster** [graalvm/native-build-tools#297]
Please add a link to the samples to the documentation page for the plugins.

The docs are great, but it is easier to miss something without being able to see complete working samples.

Also, could we add comments on what versions of unit Jupiter are supported?

Thanks!

**Comment by sbrannen** [comment]
> Also, could we add comments on what versions of unit Jupiter are supported?

The supported JUnit Platform versions are already documented for [Gradle](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#testing-support) and [Maven](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#testing-support-version-compatibility).

From that, one can infer that JUnit Jupiter 5.8 and higher is supported.

Though, explicitly stating that might prove beneficial.
