### ISSUE TITLE
InvalidPathException: Illegal char <:> at index 153:

### ISSUE THREAD

**Issue by KrishnaST** [graalvm/native-build-tools#298]
Command executed   `mvn -Pnative -DskipTests package -e -X`
Packaging failed with InvalidPathException. Logs attached.
[log.txt](https://github.com/graalvm/native-build-tools/files/9566619/log.txt)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: D:\Tools\apache-maven-3.8.6
Java version: 17.0.2, vendor: Oracle Corporation, runtime: D:\Tools\jdk-17.0.2
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

Project Dependancies - Refer to pom.xml 
[pom.txt](https://github.com/graalvm/native-build-tools/files/9566616/pom.txt)

**Comment by lazar-mitrovic** [comment]
Fixed by https://github.com/graalvm/native-build-tools/pull/295
