### ISSUE TITLE
Tasks implementing JavaForkOptions are instrumented without using -Pagent

### ISSUE THREAD

**Issue by wilkinsona** [graalvm/native-build-tools#301]
**Describe the bug**

The [documentation](https://graalvm.github.io/native-build-tools/0.9.13/gradle-plugin.html#configuration-options) states:

> By default, if `-Pagent` is specified, all tasks that extend JavaForkOptions are instrumented.

Contrary to this, instrumentation happens without `-Pagent`.

**To Reproduce**
```groovy
plugins {
	id 'java'
	id 'org.graalvm.buildtools.native' version '0.9.13'
}
```
```bash
$ gradle test
[native-image-plugin] Instrumenting task with the native-image-agent: test
```

**Expected behavior**
Tasks extending `JavaForkOptions` are only instrumented when specifying `-Pagent`.

**System Info (please complete the following information):**
 - OS: N/A
 - GraalVM Version: N/A
 - Java Version: N/A
 - Plugin version: 0.9.13

**Comment by melix** [comment]
This (confusing) message is already fixed. It says that tasks are instrumented, but they _would_ be instrumented if `-Pagent` was used.

https://github.com/graalvm/native-build-tools/pull/278

**Comment by wilkinsona** [comment]
Thanks, @melix.
