### ISSUE TITLE
Unnecessary warning emitted when using JUnit Jupiter 5.9 with Maven plugin

### ISSUE THREAD

**Issue by sbrannen** [graalvm/native-build-tools#311]
`JupiterConfigProvider` registers reflection configuration for `TimeoutExtension$ExecutorResource` as can be seen here:

https://github.com/graalvm/native-build-tools/blob/3cf049769e879840dd182a0985c3ecc55a936cc7/common/junit-platform-native/src/main/java/org/graalvm/junit/platform/config/jupiter/JupiterConfigProvider.java#L104-L109

The issue is that `TimeoutExtension$ExecutorResource` exists in JUnit Jupiter 5.8 but no longer in 5.9. Consequently, when you run native tests with JUnit Jupiter 5.9 you see the following warning.

> Warning: Could not register complete reflection metadata for org.junit.jupiter.engine.extension.TimeoutExtension$ExecutorResource. Reason(s): java.lang.IncompatibleClassChangeError: org.junit.jupiter.engine.extension.TimeoutExtension and org.junit.jupiter.engine.extension.TimeoutExtension$ExecutorResource disagree on InnerClasses attribute

**Comment by sbrannen** [comment]
Although the attempt to register reflection configuration for `TimeoutExtension$ExecutorResource` is performed defensively within a try-catch block, that defensive mechanism apparently doesn't work.

- Potentially related to #305

**Comment by sbrannen** [comment]
The Spring team confirmed that this does not occur with the Gradle plugin, hinting that it may well be directly related to #305.

**Comment by fniephaus** [comment]
I've recently updated the JUnit integration and the warning should no longer show. If that is not the case, please feel free to re-open the ticket.
