### ISSUE TITLE
Image build request failed

### ISSUE THREAD

**Issue by CRY-D** [graalvm/native-build-tools#317]
**Describe the problem**
First, when I build a simple Hello world app, it works just fine, but when I try to build my **2.5Mb jar file** I always end up with this Error message **Error: Image build request failed with exit status 137** 
just like so, any hint to overcome this obstacle?

![select-area_20220924174852](https://user-images.githubusercontent.com/16564491/192109667-db481b71-ac55-4f13-8156-cb33043b34ac.png)

**System Info:**
 - OS: [e.g. `Linux Manjaro`]
 - GraalVM Version [`GraalVM 22.1.0 Java 11 CE`]
 - Java Version [`11`]
 - C compiler: gcc (pc, x86_64, 12.2.0)
 - Garbage collector: Serial GC

**Comment by melix** [comment]
This repository isn't about `native-image` but the Maven and Gradle plugins for GraalVM native image. Your issue may be related to a firewall preventing the connection to the native image server, but it's a wild guess.

**Comment by wangliang181230** [comment]
I also encountered the same problem, I increased the memory of the virtual machine to solve it.
