### ISSUE TITLE
Unnecessary eager check for GraalVM installation breaks builds when using other JDKs

### ISSUE THREAD

**Issue by alvarosanchez** [graalvm/native-build-tools#327]
#274 introduced an unnecessary eager check for a GraalVM installation:

https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeExtension.java#L120-L124

This halts the build with the following exception:

```
[INFO] Caused by: org.apache.maven.plugin.MojoExecutionException: 'gu' tool wasn't found. This probably means that JDK at isn't a GraalVM distribution.
[INFO]     at org.graalvm.buildtools.Utils.getJavaHomeNativeImage (Utils.java:89)
[INFO]     at org.graalvm.buildtools.Utils.getNativeImage (Utils.java:121)
[INFO]     at org.graalvm.buildtools.maven.NativeExtension.afterProjectsRead (NativeExtension.java:121)
```

Because this is done so early in an extension, it breaks builds even if no NBT mojo is being invoked.

The check should only be done lazily right before the `graalvmJava` variable is needed

**Comment by snicoll** [comment]
A note that it should also be possible to invoke a Mojo of Native Build Tools that does not need GraalVM. `add-reachability-metadata` in particular.

**Comment by sdeleuze** [comment]
I start working on this and will submit a PR.

**Comment by sschuberth** [comment]
I just filed a similar issue on the Gradle build file level, see https://github.com/graalvm/native-build-tools/issues/350.
