### ISSUE TITLE
Ship repository metadata as a Maven artifact

### ISSUE THREAD

**Issue by melix** [graalvm/native-build-tools#328]
Currently, the plugin specifies a default version of the reachability metadata. If the user says nothing, we default to that version and try to fetch the metadata from the [repository GitHub releases page](https://github.com/oracle/graalvm-reachability-metadata/releases/).

However, the community has expressed interest in seeing that metadata published as a Maven artifact (that is to say, on Maven Central, in practice).

After discussions, the NBT team suggests that this project takes care of publishing such metadata on Maven Central, by publishing on Central the default version that we depend on.

In practice, I suggest to proceed with the following:

- add a Gradle task which is responsible for downloading the default version of the metadata repository
- convert that artifact into a `jar` file (because it's easier for Maven consumers to depend on a `jar` than on a `zip`)
- publish that artifact as a classified artifact of the [graalvm-reachability-metadata project](https://github.com/graalvm/native-build-tools/tree/master/common/graalvm-reachability-metadata)
- change the default URL that we use in the plugin to use Maven Central's URL for that artifact

This can possibly require some changes in the project so that we can support jars as repository format.
In addition, this raises the question of the artifact name, because the metadata repository version is _different_ from the NBT version. We could, for example, use this: `https://repo1.maven.org/maven2/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.14/graalvm-reachability-metadata-0.9.14-repository.jar`, that is to say _ignore_ the repository version. There is unfortunately no way we can encode the repository version in the artifact name while preserving the compatibility with the Maven repository format.

However, this complicates the semantics of the `version` property in the DSL: this property refers to the metadata repository version, not the NBT version. So _by default_, we would use the URL from Maven, but if the version is specified, we'd need to use the GH releases URL.

Note that this proposal doesn't change the fact that a user can specify a local file, or a full URL to a custom repository. This is really about shipping a metadata repository release as part of the NBT release, without embedding it into the NBT jar itself.

/cc @sdeleuze wdyt?

**Comment by sdeleuze** [comment]
I am confused by the mix between https://github.com/graalvm/native-build-tools/ and https://github.com/oracle/graalvm-reachability-metadata, how it impacts the version semantic and the groupId, and how people can know what metadata repository version is contained in let say `graalvm-reachability-metadata-0.9.14-repository.jar`.

Why can't we just keep separation of concerns and publish metadata properly on https://github.com/oracle/graalvm-reachability-metadata side with the proper `graalvm-reachability-metadata` version?

**Comment by melix** [comment]
> Why can't we just keep separation of concerns and publish metadata properly on https://github.com/oracle/graalvm-reachability-metadata side with the proper graalvm-reachability-metadata version?

So let's step back a bit:

1. the reachability metadata is published as a zip file on the repository releases page, but teams expressed interest in seeing it as a Maven artifact on Maven Central
2. we _can't_ easily publish the metadata as a Maven artifact, for various, non technical reasons
3. an idea was to _bundle_ the metadata repository _within_ the NBT jar, to which I expressed concerns (e.g, size of the artifacts, especially if in the end it's not used because overridden)
4. therefore I suggested in our last meeting that we take advantage that NBT are already published on Central to publish a new artifact, alongside our jars, which is the _current version_ of metadata

This issue _does not_ suggest to stop releasing repository metadata releases separately on GH: it is simply a convenience to have _some_ releases of metadata on Central.

I am not happy with the "double versioning" either, but that's a Maven repository layout restriction. Unless we encode the version _in the artifact id_, say `repository-0.2.1`, we can't do this. And even so, it would produce scary artifact names which are likely to confuse a lot of "version parsers": `repository-0.2.1-0.9.14.jar"`.

**Comment by sdeleuze** [comment]
> This issue does not suggest to stop releasing repository metadata releases separately on GH: it is simply a convenience to have some releases of metadata on Central.

I meant publishing then on Maven Central from metadata side but I guess you answered via "we can't easily publish the metadata as a Maven artifact, for various, non technical reasons" where you have the context and not me.

So let's move forward with your proposal with `graalvm-reachability-metadata-0.9.14-repository.jar` but let's maybe try to make it as clear as possible what version of the metadata repository is used for a specific NBT version by:
 - Continue to specify the metadata version used by default in a NBT property file (which will used at build time instead of runtime)
 - Make sure to create an issue when upgrading the medadata version to get this information in the release notes
 - If we can get this information on the reference documentation, even better.
