### ISSUE TITLE
Publish the Gradle plugin to the plugin portal

### ISSUE THREAD

**Issue by sschuberth** [graalvm/native-build-tools#349]
As described [here](https://github.com/graalvm/native-build-tools/blame/a3b5f3fd8d1a64a654a4cae63867532efdf2709e/docs/src/docs/asciidoc/gradle-plugin.adoc#L47), the Gradle plugin is not yet published to the [Gradle Plugin Portal](https://plugins.gradle.org). I'm not sure what the reasons are, but the current way of [manually](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#_adding_the_plugin) adding `mavenCentral()` as a plugin repository and not being able to apply the plugin just by plugin id is a bit inconvenient.

**Comment by sschuberth** [comment]
On top of that, someone seems to grabbed a confusingly similar namespace: https://plugins.gradle.org/plugin/org.graalvm.plugin.native-image

**Comment by fniephaus** [comment]
It seems adding `mavenCentral()` is no longer necessary (see https://github.com/graalvm/native-build-tools/commit/c5477c63d4166b18887bd1c987c91b4445ff5883). Also, `org.graalvm.plugin.native-image` has been removed in the meantime.

I'm not sure it still makes sense to publish the Gradle plugin to the plugin portal. Would there still be any benefit?
