### ISSUE TITLE
Unable to configure `native-gradle-plugin` project with a non-GraalVM JDK

### ISSUE THREAD

**Issue by sschuberth** [graalvm/native-build-tools#350]
Because of

https://github.com/graalvm/native-build-tools/blob/9ba6220b5ac280a1ae8e195f936afd9ab5cda670/build-logic/gradle-functional-testing/src/main/groovy/org.graalvm.build.functional-testing.gradle#L77-L80

the whole `native-build-tools` project cannot even be configured in Gradle without a GraalVM. That's a bit inconvenient for first-time contributors who just want to configure / build the project, but not run functional tests (yet).

It would be nice if the build setup could be changed so that GraalVM is only required for running functional tests, but otherwise a "regular" JDK suffices.

**Comment by sschuberth** [comment]
On a related note, I'm surprised about the `"GraalVM"` in

    vendor.set(JvmVendorSpec.matching("GraalVM"))

Shouldn't that be `"GraalVM Community"` to align with [what Gradle has](https://github.com/gradle/gradle/blob/306ff903de2efd5d2de1712aeced1d51f076937f/subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/JvmVendor.java#L30)?

**Comment by sschuberth** [comment]
I just realized the same code snippet is also at

https://github.com/graalvm/native-build-tools/blob/9ba6220b5ac280a1ae8e195f936afd9ab5cda670/native-maven-plugin/build.gradle.kts#L155-L158

**Comment by sdeleuze** [comment]
Does not impact Spring Boot 3 since we disable toolchain support by default, but still worth to fix if we can. We should probably have distinct launcher for native and non native tasks and configure them on demand if that's possible.

**Comment by melix** [comment]
This issue is about the NBT build itself, not for users, though. At the same time I'm not sure we should encourage _not_ running functional tests ;)

**Comment by sschuberth** [comment]
I wouldn't say that being able to configure / build with non-Graal *encourages* to not run functional tests locally (and they would be run in CI as part of PRs anyway).

In any case, looking for a "Graal" vendor spec instead of "Graal Community" further complicates things, as this way one cannot just point the `org.gradle.java.installations.paths` Gradle property to a GraalVM CE installation for [Gradle's toolchain auto-detection to pick it up](https://docs.gradle.org/current/userguide/toolchains.html#sec:custom_loc).

**Comment by melix** [comment]
Can you clarify why `Graal` doesn't work for you? It's an _include_ spec, so `GraalVM Community` _includes_ the term `Graal`. It is typically picked up here, from sdkman.

**Comment by sschuberth** [comment]
> It's an _include_ spec, so `GraalVM Community` _includes_ the term `Graal`.

Looks like [you're right](https://github.com/gradle/gradle/blob/fbe9699332c66d9dc7d28aaa4982f7ffc7aab81a/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultJvmVendorSpec.java#L34-L36). I was first looking at the wrong code in `DefaultJvmVendorSpec` (and didn't just try it out).

**Comment by alvarosanchez** [comment]
GraalVM should be used to work on this project's build.

**Comment by sschuberth** [comment]
> GraalVM should be used to work on this project's build.

Out of curiosity, can you also provide an objective reason for this?

**Comment by alvarosanchez** [comment]
> > GraalVM should be used to work on this project's build.
> 
> Out of curiosity, can you also provide an objective reason for this?

This project is about providing build tooling support for creating native executables. It has quite some tests that use GraalVM Native Image, and then make assertions out of that. Writing tests (and obviously, running the existing ones) is the way we use to ensure everything works (and nothing else breaks).

I see your point about first-time contributors, but honestly, if they managed to install a non-GraalVM JDK, surely they will know how to install GraalVM

**Comment by sschuberth** [comment]
> if they managed to install a non-GraalVM JDK, surely they will know how to install GraalVM

At least it will get easier when https://github.com/graalvm/native-build-tools/issues/100 gets resolved, so I'll close this.

**Comment by alvarosanchez** [comment]
You should check [this](https://medium.com/graalvm/one-line-graalvm-jdk-downloads-91ee8d4e6ffd)

**Comment by sschuberth** [comment]
> You should check [this](https://medium.com/graalvm/one-line-graalvm-jdk-downloads-91ee8d4e6ffd)

Thanks, but I'm really just interested in letting Gradle bootstrap it.
