### ISSUE TITLE
Fix SNAPSHOTS repository

### ISSUE THREAD

**Issue by artemik** [graalvm/native-build-tools#365]
Please fix SNAPSHOTS repository. Currently (and it's mentioned in the docs) `https://raw.githubusercontent.com/graalvm/native-build-tools/snapshots` doesn't work.

For example, the latest SNAPSHOT is critical to get the latest GraalVM 22.3.0 working, which was fixed in https://github.com/graalvm/native-build-tools/pull/364

**Comment by melix** [comment]
We're having reliability issues with the SNAPSHOT repository. Note that the fix you mention is not merged yet, so having the SNAPSHOT repo wouldn't help.

However, if you are using Gradle, you may have luck trying the [includegit Gradle plugin](https://melix.github.io/includegit-gradle-plugin/latest/index.html) which would let you build from sources by adding this to your `settings.gradle` file:

```gradle
plugins {
    id 'me.champeau.includegit' version '0.1.5'
}

rootProject.name="repro"

gitRepositories {
    include('graalvm') {
        uri = 'https://github.com/sdeleuze/native-build-tools.git'
        branch = '0.9.18-fixes'
    }
}

```

**Comment by melix** [comment]
Fixed by https://github.com/graalvm/native-build-tools/commit/b339e418d35a2410c3f68b0695a4861eb1138cbe (but the underlying problem still remains to be fixed)
