### ISSUE TITLE
GraalVM version check fails to detect that 23.0.0 is newer than 22.3.0

### ISSUE THREAD

**Issue by fniephaus** [graalvm/native-build-tools#384]
When trying to build a native Spring helloworld, the build fails with the following error if I use a GraalVM 23 dev build:

> GraalVM version 22.3 is required but 23.0 has been detected, please upgrade.

I'm not sure whether Spring wants to make sure that only 22.3 is accepted or whether it's fine to use a newer version. So either:

1) we need to make sure that the version check takes semantic versioning into account (22.3.0 < 23.0.0) or
2) we should adjust the error message to something like:
> GraalVM version 22.3 is required but 23.0 has been detected, please make sure that you use the required GraalVM version.

As a side node: I currently have to hardcode the version to some number because when I build GraalVM from source, the reported version is `dev`. Should we extend the version check so that it always accepts `dev` and maybe prints a warning in that case?

/cc @sdeleuze

**Comment by sdeleuze** [comment]
I can indeed reproduce.

**Comment by sdeleuze** [comment]
@fniephaus Could you please share what returns `native-image --version` when built from sources?
