### ISSUE TITLE
Gradle collectReachabilityMetadata hangs indefinitely

### ISSUE THREAD

**Issue by jonatan-ivanov** [graalvm/native-build-tools#387]
**Describe the bug**
With the latest version of the plugin (0.9.19), the latest version of Gradle (7.6) and GraalVM (22.3.0 CE, Java 17), on latest MacOS (Ventura 13.1, x86), the `collectReachabilityMetadata` task seems to hang indefinitely (our CI build [kills the process](https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer-samples/275/workflows/f48f3653-d43e-4f84-8451-765ff57827cc/jobs/405) after an hour).

**To Reproduce**
The project that can reproduce the issue is [public](https://github.com/micrometer-metrics/micrometer-samples/tree/main/micrometer-samples-native-image). It is part of a multi-project build (I'm not sure if this is relevant), in the configuration we [set the `javaLauncher`](https://github.com/micrometer-metrics/micrometer-samples/blob/main/build.gradle#L143-L172C6) and [the `mainClass`](https://github.com/micrometer-metrics/micrometer-samples/blob/bca9ec2741ab5649ce794770bd400acd4b1695df/micrometer-samples-native-image/build.gradle#L37C16-L42).

Executing
```bash
./gradlew clean build
```
should reproduce the issue.

A few interesting details:
- The issue seems to be intermittent. After I kill the process and rerun the task, it usually works and I can't reproduce for a while. I tried killing the daemons, removing the Gradle Enterprise plugin (remote cache), the local disk cache, and the project's `.gradle` folder which makes the issue kind of reproducible
- The `collectReachabilityMetadata` task is executed even if there is no native tasks involved (e.g.: `./gradlew build`)
- `./gradlew tasks` fails because:
```
Execution failed for task ':tasks'.
> Could not create task ':micrometer-samples-native-image:collectReachabilityMetadata'.
   > Cannot set the value of task ':micrometer-samples-native-image:collectReachabilityMetadata' property 'metadataService' of type org.graalvm.buildtools.gradle.internal.GraalVMReachabilityMetadataService using a provider of type org.graalvm.buildtools.gradle.internal.GraalVMReachabilityMetadataService.
```

**Expected behavior**
The `collectReachabilityMetadata` finishes it's job in a reasonable time.

**Logs**
N/A

**System Info:**
 - OS: `Mac OS X 13.1 x86_64`
 - GraalVM Version: `GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)`
 - Java Version: `openjdk 17.0.5 2022-10-18`
 - Plugin version: `native-gradle-plugin:0.9.19`

**Additional context**
```
 ❯ gradle --version

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (GraalVM Community 17.0.5+8-jvmci-22.3-b08)
OS:           Mac OS X 13.1 x86_64

 ❯ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```

**Comment by jonatan-ivanov** [comment]
I have an update.

Looking at the thread dump, it seems `Execution worker Thread 6` is `BLOCKED` because of `Execution worker Thread 8`. But `Execution worker Thread 8` is awaiting on a notification, see the thread dump: [gradle-daemon-threaddump-1674241510713.zip](https://github.com/graalvm/native-build-tools/files/10485802/gradle-daemon-threaddump-1674241510713.zip).

We have a multi-project build and more than one sub-projects use the native plugin. When this happens I see two `collectReachabilityMetadata` tasks hanging so I'm suspicious that the task is not thread-safe and concurrent execution drives them into deadlock.

It seems if I do a hack and don’t let them run in-parallel they don’t hang.

**Comment by melix** [comment]
Thanks for the info, I was able to reproduce the problem and I have a PR which fixes it. It is indeed a problem with the metadata collecting service which is not supposed to be called concurrently.
