### ISSUE TITLE
Make project runnable without GRAALVM_HOME variable

### ISSUE THREAD

**Issue by dnestoro** [graalvm/native-build-tools#390]
**Is your feature request related to a problem? Please describe.**
Project requires `GRAALVM_HOME` environment variable to be set. 

**Describe the solution you'd like**
It would be nice to be able to run the project without setting `GRAALVM_HOME` as an environment variable, and have only `JAVA_HOME` configured.

**Additional context**
The issue is based on [this](https://github.com/graalvm/native-build-tools/pull/343#issuecomment-1400437943) comment.

**Comment by sdeleuze** [comment]
I think this issue is specific to the agent support.

**Comment by sdeleuze** [comment]
Can't reproduce anymore.
