### ISSUE TITLE
[QUESTION] Is it possible to build native image of several maven sub-modules using a single command in their common parent module ?

### ISSUE THREAD

**Issue by johanHenix** [graalvm/native-build-tools#411]
Hello,

I have a maven parent module inheriting from micronaut-parent with several sub-modules and I want to create the native image of each sub-module with a single maven command in the parent module.

```
parent-module
|
|- sub-module-A (native-image-A)
|
|- sub-module-B (native-image-B)
```
Parent module holds some micronaut dependencies.
Each sub-module has the following build:
```
    <build>
        <plugins>
            <plugin>
                <groupId>io.micronaut.build</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
            </plugin>
        </plugins>
    </build>
```

and the following profiles:
```
    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${native.maven.plugin.version}</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                            <execution>
                                <id>test-native</id>
                                <goals>
                                    <goal>test</goal>
                                </goals>
                                <phase>test</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <imageName>${native-image-name}</imageName>
                            <buildArgs>
                                <arg>-H:ReflectionConfigurationFiles=src/main/resources/reflection-config.json</arg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

**Expected:**

I would like to build each sub-module native image with a single command :
```
cd parent-module
mvn -Pnative package
```

Then the native images would be built in respective target directories of each sub-module.

**Actual:**

Trying this, I encounter several errors:

During goal test-native (or build-native if I skip tests) of sub-modules:
`Error: The reflection configuration file "(...)/parent-module/src/main/resources/reflection-config.json" does not exist.`

Even during sub-modules build, it seems to search for the reflection-config.json file in parent module.

If I copy reflection-config.json at the mentioned path, I get an error during tests if I use a `new FileInputStream("my/relative/path")` in one of the tests:
`java.io.FileNotFoundException: src/test/resources/hello.txt (No such file or directory)`

Again, it seems to search the test resource file in parent module.

**Workaround:**
I found a way to do this by copying resources to the parent module and deleting them afterwise but this solution is not really clean.

Note that everything works fine if I build native images individually in each sub-module.

**System Info:**
OS: Windows 10 / Generating native images on WSL2
GraalVM Version: 22.3.0
Java Version: 11
Plugin Version (native-maven-plugin): 0.9.19

**To reproduce:**
You can reproduce the issue with this simple repository: https://github.com/johanHenix/micronaut-parent-module/

Thank you !

**Comment by melix** [comment]
This should be a question for the Micronaut Maven plugin, not this one. /cc @alvarosanchez

**Comment by alvarosanchez** [comment]
@johanHenix please create an issue at https://github.com/micronaut-projects/micronaut-maven-plugin/

**Comment by johanHenix** [comment]
Sorry I misplaced the issue, thanks for your support.
