### ISSUE TITLE
Create standard annotations and annotation processor for META-INF/native-image/reflect-config.json

### ISSUE THREAD

**Issue by sewe** [graalvm/native-build-tools#413]
**Is your feature request related to a problem? Please describe.**

AFAIK, there are several libraries of annotations plus associated annotation processors to generate `META-INF/native-image/reflect-config.json` configuration files. For example, [formkiq/graalvm-annotations](https://github.com/formkiq/graalvm-annotations), [GoodforGod/graalvm-hint](https://github.com/GoodforGod/graalvm-hint), [palantir/graal-annotations](https://github.com/palantir/graal-annotations).

Alas, they all differ slightly and, sometimes, are not quite up-to-date with the latest `native-image` developement, e.g., still placing the generated files in `META-INF/graal` instead of `META-INF/native-image`.

It would IMHO hence be benefical to the GraalVM ecosystem to have a standard set of annotations (and a default annotation processor).

**Describe the solution you'd like**

The existing annotations are already pretty good (and all admittedly rather close to the underlying `reflect-config.json` format), so the big advantage of having annotations and annotation processor under the roof of the GraalVM project is standardization.

It should, however, be possible to pass a prefix to the annotation processor to tweak the path: `META-INF/native-image/${nativeImageConfigPrefix}/reflect-config.json`. With Maven, for example, one could then use

```xml
<compilerArgs>
     <arg>-AnativeImageConfigPrefix=${project.groupId}/${project.artifactId}</arg>
</compilerArgs>
```

This is not supported by all current implementations.

**Describe alternatives you've considered**

Use one of the existing sets of annotations and, if it turns out to be no longer maintained, perform a search-and-replace migration to a different set with (hopefully) the same semantics. 🤞🏻

**Comment by vjovanov** [comment]
We are considering adding the standard annotations that are based on reachability (as opposed to other annotation approaches). However, until this is not implemented I would try to use system properties for the unification. 

It would be the responsibility of the annotation-library authors use the same property for the destination directory. I guess opening a ticket on the individual projects would be the way to go.
