### ISSUE TITLE
Native maven plugin agent not compatible with Maven 3.9.x

### ISSUE THREAD

**Issue by justin-tay** [graalvm/native-build-tools#418]
When using the agent with Maven 3.9.x the following error is seen.

```java
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.21-SNAPSHOT:merge-agent-files (test-native) on project maven: Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.21-SNAPSHOT:merge-agent-files failed: A required class was missing while executing org.graalvm.buildtools:native-maven-plugin:0.9.21-SNAPSHOT:merge-agent-files: org/codehaus/plexus/util/FileUtils
[ERROR] : org.codehaus.plexus.util.FileUtils
```

This is because since Maven 3.9.0 they are no longer silently introducing an old version of `plexus-utils`. See https://issues.apache.org/jira/browse/MNG-6965.

Either the dependency needs to be explicitly defined or the code in `MergeAgentFilesMojo` needs to be rewritten to remove the dependency on `plexus-utils`.

https://github.com/graalvm/native-build-tools/blob/0ead2626d7f3f8f215f4c9a4d44cfe86cd5834f3/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/MergeAgentFilesMojo.java#L48

**To Reproduce**

Use Maven 3.9

Use the `java-application-with-reflection` sample at https://github.com/graalvm/native-build-tools/tree/master/samples/java-application-with-reflection

`mvn -Pnative test -Dagent`

**Comment by alvarosanchez** [comment]
IMO usages of `org.codehaus.plexus.util.FileUtils` should be removed

**Comment by linghengqian** [comment]
- According to https://issues.apache.org/jira/browse/MNG-6965.
```
1.The "special status" of plexus-utils is gone, hence you must declare it as any other dependency. Maven runtime does NOT provide it (that comment is wrong). Hence, "compile" scope is proper scope.
2.Again, plexus-utils starting with Maven 3.9.x is "just" a plain dependency, your Mojo at runtime will use version you declared in your POM (unless overridden by users of your plugin in their POM as plugin dependency).
```
- To ensure some level of compatibility, I don't think the use of `org.codehaus.plexus.util.FileUtils` should be removed. Dependencies for `plexus-utils-3.5.1.jar` should be explicitly declared in `native-build-tools`.
