### ISSUE TITLE
`@Nested` test classes are not supported.

### ISSUE THREAD

**Issue by michael-simons** [graalvm/native-build-tools#45]
First of all: Big kudos for a project.

I was eager to try this out on https://github.com/neo4j-contrib/cypher-dsl. We do have a lot of `@Nested` classes, however.

Changing the `App2Test` class in your example code like this

```java
package org.graalvm.buildtools.example;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class App2Test {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Nested
    class ANestedTest {

        @Test
        void apphasNestedGreetingToo() {
            App classUnderTest = new App();
            assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        }
    }
}
```

will fail in Maven `mvn -Pnative test` with 

```
junit-platform-native] Running in 'test listener' mode.
Fatal error:java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Class org.graalvm.buildtools.example.App2Test$ANestedTest cannot be instantiated reflectively . It does not have a nullary constructor.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

The same result will happen with the Gradle project, even when the agent is used (with a workaround specified in this issue https://github.com/graalvm/native-build-tools/issues/44) 

I have attached the generated native image files.
[test.zip](https://github.com/graalvm/native-build-tools/files/6649728/test.zip)

Class is registered for reflection, but something still is odd.

**Comment by gradinac** [comment]
Hey @michael-simons! This should now be fixed on master, I'll post a comment here once a new version of the plugin is out - it would be great if you could test it out once it's released :)

**Comment by michael-simons** [comment]
I can confirm that `@Nested` now works with 0.9.1-SNAPSHOT. This is great, thank you!
