### ISSUE TITLE
[QUESTION] Which version graalvm is used in 0.9.22?

### ISSUE THREAD

**Issue by GrapeBaBa** [graalvm/native-build-tools#451]

**Comment by vjovanov** [comment]
What is the question?

**Comment by dnestoro** [comment]
Hey @GrapeBaBa, we don't have the default version of GraalVM that Native Build Tools are using. Instead user should specify which version wants to use. All versions that we are using by default are [here](https://github.com/graalvm/native-build-tools/blob/master/gradle/libs.versions.toml). GraalVM version defined [here](https://github.com/graalvm/native-build-tools/blob/master/gradle/libs.versions.toml#L12) is only used for testing inside repo.
