### ISSUE TITLE
What is needed to run a native image?

### ISSUE THREAD

**Issue by EugenMayer** [graalvm/native-build-tools#462]
I'am compiling a simple spring-boot app via a the gradle plugin. (using graalvm 17.07 CE)

I'am compiling it under Manjaro (6.1.31-2-MANJARO/ldd (GNU libc) 2.37).

When running the app, it does work under (using docker as a runtime to simulate)

- debian:bookworm
- ubuntu:latest
- fedora:latest

It does fail under
- debian:buster (`./app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./app)`)
- debian:bullseye (`./app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./app`)
- alpine (`exec ./app: no such file or directory`)
- busybox (`./app: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`)

i run them all using

```
 docker run -v ./build/native/nativeCompile:/app -w /app <image> ./app
```

Is it (again) all about the `glibc` version and if want to run it under `debian:buster` (not even on the docker image, rather on a baremetal) in the end, i need to compile it using the same glibc version (or just inside a docker image) and so on? Basically the same limitations that apply to any current linux cpp app.

Any further hints / corrections here? Thanks!

**Comment by wghdir** [comment]
You can try add --static in buildArgs,It in native-maven-plugin configuration

**Comment by EugenMayer** [comment]
Closing this question since the answer is what it is. Graalvm is of course a Cpp based application with all the limits and issue one has with distributing a linux-cpp app for different distros

 - glibc version is relevant (static will not help with this either)

At least one does not depend on a lot more then glibc (and maybe something else i do not know yet) when building a graalvm based application - in contrast to a common cpp app (of course one can use static for most of those libraries, but this sounds way more romantic/easy as it is).
