### ISSUE TITLE
[QUESTION] Multiple warnings when running nativeCompile with Gradle and Spring Boot

### ISSUE THREAD

**Issue by vbaidak** [graalvm/native-build-tools#464]
**Describe the problem**
So, I'm executing `clean nativeBuild --warning-mode all` and got multiple warnings such as:

```
Warning: Could not resolve class com.sun.el.ExpressionFactoryImpl for reflection configuration. Reason: java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl.

WARNING: Cannot register dynamic proxy for interface list: org.jline.terminal.impl.jna.linux.CLibrary. Reason: Class org.jline.terminal.impl.jna.linux.CLibrary not found.
```
See the complete [output.txt](https://github.com/graalvm/native-build-tools/files/11970183/output.txt)
The build, however, is successful.
I checked some of the warnings and saw that these classes are not used as dependencies. However, when I add a library (as an `implementation` scope) containing these classes (such as `javax-el`), the warning disappears.

I'm implementing `spring-shell` with `spring-boot` (see the complete [build.gradle.kts](https://github.com/graalvm/native-build-tools/files/11970222/build.gradle.kts.txt))
So the question is what am I missing?

**Additional context**

**System Info (please complete the following information):**
 - OS: Microsoft Windows 11 Pro 10.0.22621 Build 22621
 - GraalVM Version: 23.0.0

 - Java Version: 17.0.7+8.1
 - Plugin version: org.graalvm.buildtools.native:0.9.23

**To Reproduce**
Just use the attached build.gradle file and run `nativeCompile`

**Comment by vbaidak** [comment]
@melix , thanks for the explanation. My app is running perfectly with all the warnings indeed. It would be better, however, to have some configuration where we can ignore warnings for packages etc. (something similar to what we have in **ProGuard**)

**Comment by melix** [comment]
This cannot be implemented in the build tools though, this is something in `native-image` itself. You could consider creating an issue in https://github.com/oracle/graal instead. I'm closing this one since your concern has been addressed.
