### ISSUE TITLE
Introduce automated tests for the Gradle and Maven plugins

### ISSUE THREAD

**Issue by sbrannen** [graalvm/native-build-tools#48]
In order to avoid bugs such as #44, the native build tools project should introduce automated tests for the Gradle and Maven plugins.

This can be achieved in various ways.

For Gradle, one option may be to use the [Gradle TestKit](https://docs.gradle.org/current/userguide/test_kit.html).

Another option is the approach taken by the JUnit team in the [platform-tooling-support-tests](https://github.com/junit-team/junit5/tree/main/platform-tooling-support-tests) project, where individual [demo projects](https://github.com/junit-team/junit5/tree/main/platform-tooling-support-tests/projects) are tested in isolation.

**Comment by lazar-mitrovic** [comment]
> Another option is the approach taken by the JUnit team in the platform-tooling-support-tests project, where individual demo projects are tested in isolation.

We are already doing a similar thing [here](https://github.com/graalvm/native-build-tools/blob/4aff5ee1c3cfdcaf16084658c442c0691c58a2c7/.github/workflows/native-gradle-plugin.yml#L48-L55), so easiest fix might be to populate `examples` directory with multiple examples for each supported build tool.

**Comment by sbrannen** [comment]
> We are already doing a similar thing [here](https://github.com/graalvm/native-build-tools/blob/4aff5ee1c3cfdcaf16084658c442c0691c58a2c7/.github/workflows/native-gradle-plugin.yml#L48-L55), so easiest fix might be to populate `examples` directory with multiple examples for each supported build tool.

Does that actually perform some form of verification of the results (assertions, etc.)? If so, what is the error reporting like?

Or does it just _run_ something and hope there's no bad exit code of the executed command?

**Comment by lazar-mitrovic** [comment]
Fixed by #87
