### ISSUE TITLE
Add concurrency to github actions

### ISSUE THREAD

**Issue by dnestoro** [graalvm/native-build-tools#481]
**Is your feature request related to a problem? Please describe.**
GitHub actions takes too much time to complete (for my [last PR](https://github.com/graalvm/native-build-tools/actions/runs/5798717072), more than 5 hours).

**Describe the solution you'd like**
Add concurrency to github actions so the job can be split between GitHub actions workers

**Comment by fniephaus** [comment]
Similar to what we have in the metadata repo, we probably also need to job that enumerates all jobs and spawns corresponding build jobs.

**Comment by dnestoro** [comment]
Done [here](https://github.com/graalvm/native-build-tools/pull/482)
