### ISSUE TITLE
Windows 10: native-maven-plugin:0.9.0 looks  for JAVA_HOME\lib\svm\bin\native-image.exe but it's actually in JAVA_HOME\jre\lib\svm\bin

### ISSUE THREAD

**Issue by AlSherif** [graalvm/native-build-tools#49]
`mvn -Pnative package -DskipTests`

fails with: 
```
Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.0:build (build-native) on project platform: Building image with C:\tools\graalvm-ce-java8-21.1.0\lib\svm\bin\native-image.exe failed: Cannot run program "C:\tools\graalvm-ce-java8-21.1.0\lib\svm\bin\native-image.exe"
```

I assume that it is looking for `C:\tools\graalvm-ce-java8-21.1.0\jre\lib\svm\bin\native-image.exe`.

Before I was using `org.graalvm.nativeimage:native-image-maven-plugin` and it worked fine.

**Comment by geqilong** [comment]
set JAVA_HOME=C:/tools/graalvm-ce-java8-21.1.0/jre before run "mvn -Pnative package -DskipTests"
The problem probably lies in "org.graalvm.buildtools.Utils#getNativeImage".
