### ISSUE TITLE
Maven Native plugin fails on POM packaging projects

### ISSUE THREAD

**Issue by stevenschlansker** [graalvm/native-build-tools#490]
I am adding native-image support to an open source project by user request. I would like to run all of my project's tests through the native build pipeline in order to verify that the provided `native-image.properties` configuration works. I add `native-maven-plugin` `test-native` per documentation to the project parent pom.

`jar` packaging projects work fine, but we have a few `pom` packaging projects (like a BOM) and these fail with:
```
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.24:compile-no-fork (build-native)
   on project jdbi3-bom: Image classpath is empty. Check if your classpath configuration is correct. -> [Help 1]
```

The project is a POM, there is no classpath, and this is okay. Should the native-maven-plugin skip such projects entirely?

Workaround: add a file-missing activation to the `native` profile, and then create that file in each project you wish to skip native processing.

**Comment by alvarosanchez** [comment]
This plugin should only be added to the projects where it should run.

The correct solution is to **declare** the plugin and its configuration in your parent POM in the `pluginManagement` section, and then **reference** the plugin in each of the subprojects where it should run.

**Comment by stevenschlansker** [comment]
That means that for each of 20 projects that want to use it, I have to declare it separately, just to exclude 2 :(

**Comment by alvarosanchez** [comment]
In that case, you can configure the plugin in your parent POM as you are doing now, then in those 2 projects override the configuration and set `<skipNativeBuild>`.
