### ISSUE TITLE
doc: clarify what "Enable toolchain support to automatically" means

### ISSUE THREAD

**Issue by pjonsson** [graalvm/native-build-tools#505]
**Describe the bug**
https://graalvm.github.io/native-build-tools/0.9.26/gradle-plugin.html#_installing_graalvm_native_image_tool

says:

![image](https://github.com/graalvm/native-build-tools/assets/2082449/e2d9e1c6-2ee6-4f54-baaa-80a293c8973f)

I'm not sure if this is a rendering issue but I get the same result on Chromium and Firefox on Ubuntu 22.04 LTS. The phrasing "Enable toolchain support to automatically" is difficult to understand.

**Comment by dnestoro** [comment]
@pjonsson Thank you for reporting

**Comment by dnestoro** [comment]
@pjonsson [changes are published](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#_installing_graalvm_native_image_tool)
