### ISSUE TITLE
native-maven-plugin 0.9.27 breaks windows builds complaining about illegal chars in path on GH ci.

### ISSUE THREAD

**Issue by michael-simons** [graalvm/native-build-tools#511]
**This affects the Maven plugin.**

Native build under Windows started to fail with 0.9.27 and logs looking like this

```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <�> at index 3: D:\�a\�garmin-babel\�garmin-babel\�app\�target\�garmin-babel.app-1.0.0-SNAPSHOT.jar
2023-09-18T04:57:50.0945546Z 	at java.base@17.0.5/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
```

This happens on GitHub CI, for several projects.

Here's the simplest I have:
https://github.com/michael-simons/garmin-babel/actions/runs/6218317890/job/16874625263#step:6:109

Project source encoding is configured:
https://github.com/michael-simons/garmin-babel/blob/caa769b63e8d963d6ff66f6f2c8e8bee2c8cb8ac/pom.xml#L90

The section in question for the native-image plugin:

https://github.com/michael-simons/garmin-babel/blob/caa769b63e8d963d6ff66f6f2c8e8bee2c8cb8ac/app/pom.xml#L225-L247

And the workflow that fails:

https://github.com/michael-simons/garmin-babel/blob/caa769b63e8d963d6ff66f6f2c8e8bee2c8cb8ac/.github/workflows/release.yml#L48-L86

I don't have a "real" windows machine at hand, so this is all the information I can give you atm, sorry about that.

**Comment by olpaw** [comment]
@fniephaus looks like the recently added Windows fix has some unintended side effects.

**Comment by fniephaus** [comment]
Ouch, maybe we should revert to the old escaping strategy. And we certainly need to bring the Windows gates back up.
