### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by Hayderhammami** [graalvm/native-build-tools#512]
**Is your feature request related to a problem? Please describe.**
**Please make sure that you are using the latest plugin version, and that similar feature hasn't been [requested before](https://github.com/graalvm/native-build-tools/issues).**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fniephaus** [comment]
You're request doesn't say what we can help you with. Please feel free to leave a comment if you still need help.
