### ISSUE TITLE
Why can't I use type-safe processAot in gradle build-logic  

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [graalvm/native-build-tools#536]
**Describe the problem**
I'm using gradle to build my project, I've defined a plugin 'spring-boot-native-dubbo-application', I want to configure some native public configuration in it, But I found it impossible to type safely use 'tasks.processAot' in the plugin 'spring-boot-native-dubbo-application' :
![image](https://github.com/graalvm/native-build-tools/assets/51226051/da55847b-e48b-49b8-9e17-14986badb6a6)
![image](https://github.com/graalvm/native-build-tools/assets/51226051/2e043f64-a5c5-4018-80a3-c379e515341f)
But in a project that uses the 'spring-boot-native-dubbo-application' plugin, it is possible to type safely configure 'tasks.processAot'
![image](https://github.com/graalvm/native-build-tools/assets/51226051/cfb3e035-6f5c-45f3-93ef-f0127ebd6e5f)
![image](https://github.com/graalvm/native-build-tools/assets/51226051/3b398c95-f230-4995-a6d8-67df9214fe8f)
But that would be tedious, because it would have to be configured for every project that uses native. Is there any way to configure 'tasks.processAot' in a common way?

**System Info (please complete the following information):**
 - OS: window10
 - GraalVM Version 8.4
 - Java Version graalvm 21
 - Plugin version 0.9.28

**Comment by melix** [comment]
This isn't the correct repository : your question should be asked on the Spring Boot plugin, which adds AOT: this task is not created by the native build tools plugins.
