### ISSUE TITLE
Native image build failed with bouncycastle as JCA provider

### ISSUE THREAD

**Issue by davidl789** [graalvm/native-build-tools#544]
I'm building a native executable (Spring Boot 3.1.5) with bouncycastle as JCA provider.
Native build options:
-H:-EnableSecurityServicesFeature
-H:AdditionalSecurityProviders=sun.security.provider.Sun,sun.security.rsa.SunRsaSign,org.bouncycastle.jce.provider.BouncyCastleProvider

The native build failed with error "Detected an instance of Random/SplittableRandom class in the image heap", more details in attachment 
[random-seed-in-image-heap-error.txt](https://github.com/graalvm/native-build-tools/files/13506155/random-seed-in-image-heap-error.txt)

I attempted to resolve it by adding --initialize-at-run-time=sun.security.ssl.SSLContextImpl$AbstractTLSContext but results with more traces, more culprit classes have been added to the list but I'm still unable to resolve it.

**Comment by melix** [comment]
Closing as this is not an issue with the build plugins, but a user question. Please use one of the support channels listed here: https://www.graalvm.org/support/, thank you!
