### ISSUE TITLE
The URL of `quick build mode` has become a dead link

### ISSUE THREAD

**Issue by linghengqian** [graalvm/native-build-tools#559]
**Describe the bug**
**Make sure that you have read [the documentation](https://graalvm.github.io/native-build-tools) and that you are using the latest plugin version.**

- The URL of `quick build mode` has become a dead link. See https://blogs.oracle.com/java/post/graalvm-enterprise-221%E2%80%94%E2%80%8Bfaster-smarter-leaner in https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration-options .

**To Reproduce**

When possible, provide a link to a repository which reproduces the issue, with instructions on how to use.
The reproducer **must** make use of either the Maven or Gradle plugin.

1. Open https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration-options .
2. Open the URL in `<quickBuild>`.
3. https://blogs.oracle.com/java/post/graalvm-enterprise-221%E2%80%94%E2%80%8Bfaster-smarter-leaner has become a dead link.

Please use backticks to [properly format code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).
If possible please attach a complete reproducer here (either as [a zip file](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to public repository/branch).

**Expected behavior**

- https://blogs.oracle.com/java/post/graalvm-enterprise-221%E2%80%94%E2%80%8Bfaster-smarter-leaner should be accessible normally.

**System Info (please complete the following information):**
 - OS: [e.g. `Windows`] `Ubuntu`
 - GraalVM Version [e.g. `22.0 CE`] `23.0.1 CE`
 - Java Version [e.g. `17`] `17`
 - Plugin version [e.g. `native-gradle-plugin:0.9.10`] `native-maven-plugin:0.9.28`

**Additional context**

- Null.

**Comment by fniephaus** [comment]
Thanks for raising this, @linghengqian.

We may want to link the [quick build docs](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md#qbm-use-quick-build-mode-for-faster-builds) instead. There also is the [release announcement blog post](https://medium.com/graalvm/b7ac9a0f6066).
