### ISSUE TITLE
When run -Pagent the reflection-config.json include Test classes

### ISSUE THREAD

**Issue by jarpz** [graalvm/native-build-tools#56]
When run:
```
gradle -Pagent test
```

The reflection-config.json includes test classes, Is there any way to "filter" those classes in the generated file?.

I saw an "agent-filter.json" but there is not documentation about it.

Regards

**Comment by ScottPierce** [comment]
Does it matter if it includes reflection information for classes that are not actually compiled into the application?

**Comment by jarpz** [comment]
> Does it matter if it includes reflection information for classes that are not actually compiled into the application?

Yeah, native image generation fails because in the classpath those classes are not present. So you have to add the 
```
-H:+AllowIncompleteClasspath
```

**Comment by lazar-mitrovic** [comment]
You can use 
`gradle -Pagent run`
if you want to generate agent output for `main` source set.

Filtering of classes which are detected during agent run is done using [agent-filter files](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#agent-advanced-usage). Advanced configuration of native-image-agent isn't (at the moment) exposed to the end-user trough our plugins (you could work around that by changing JVM parameters when invoking said build tools).

`agent-filter.json` which is present in the Gradle plugin is only used for filtering out internal Gradle classes (which are detected if `run` task is invoked in the same JVM as the Gradle process itself).

**Comment by lazar-mitrovic** [comment]
I opened a new issue about fixing this error message: https://github.com/graalvm/native-build-tools/issues/65
