### ISSUE TITLE
`metadata-copy` should follow recommendation

### ISSUE THREAD

**Issue by fniephaus** [graalvm/native-build-tools#579]
[On the GraalVM website](https://www.graalvm.org/latest/reference-manual/native-image/overview/BuildConfiguration/), we recommend to put metadata into directory following this pattern:

> foo.jar has its configurations in META-INF/native-image/foo_groupID/foo_artifactID
> bar.jar has its configurations in META-INF/native-image/bar_groupID/bar_artifactID

It seems that the `metadata-copy` copies metadata into just [`/META-INF/native-image`](https://github.com/graalvm/native-build-tools/blob/c791bf6d32067664d87d58938f771f8a1cf2b42d/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/MetadataCopyMojo.java#L70).
Would be great if we could adjust it so that it follows our recommendation.

**Comment by vjovanov** [comment]
@dnestoro is this issue fixed?

**Comment by dnestoro** [comment]
Kind of... for gradle we are just suggesting (in our docs) where should user copy metadata files (and we won't have default value for it in the plugin implementation), while maven has actual default directory for metadataCopy task. 

So this issue can be closed
