### ISSUE TITLE
nativeTest Doesn't look to the right directory for the generated agent files

### ISSUE THREAD

**Issue by ScottPierce** [graalvm/native-build-tools#58]
It appears that running `./gradlew -Pagent :example:test` generates files to the `project-root/example/build/native/agent-output/test` directory. 

<img width="282" alt="Screen Shot 2021-06-17 at 5 56 40 PM" src="https://user-images.githubusercontent.com/871169/122477256-6fefdf00-cf95-11eb-98c6-df834785a33c.png">

But when I run `./gradlew -Pagent :example:nativeTest` it gives me the following error:
```
Agent output missing while `agent` option is set.
  Did you run the test task before with `-Pagent` enabled?
```

Clearly it must be looking for the agent output in the wrong directly, as the generated files are there.

**Comment by jarpz** [comment]
IF you run as: ```gradle -Pagent test -DpersistConfig ``` it will put the files over src/test/resources/META-INF/native-image

Also this error is already reported over #44

**Comment by ScottPierce** [comment]
Thanks jarpz. That appears to work.
