### ISSUE TITLE
The build of the task `:native-gradle-plugin:functionalTest` in the master branch failed in Oracle GraalVM For JDK 23.ea.13

### ISSUE THREAD

**Issue by linghengqian** [graalvm/native-build-tools#606]
**Before reporting**

- This repository should be used to report **issues on the Maven or Gradle plugins for GraalVM**.
- Please report issues which are specific to [the Spring Framework](https://spring.io/) or [the Micronaut framework](https://micronaut.io/) to their specific repositories.
- Do not report issues with building your specific application, e.g errors which happen at image build time like classes initialized at build time, or missing classes as run time: those are not related to the plugins but problems with configuration. You can refer to the [GraalVM native image documentation](https://www.graalvm.org/latest/reference-manual/native-image/) for available options and the [plugins documentation](https://graalvm.github.io/native-build-tools) for how to use them with the plugin.

**Describe the bug**
**Make sure that you have read [the documentation](https://graalvm.github.io/native-build-tools) and that you are using the latest plugin version.**

- The build of the task `:native-gradle-plugin:functionalTest` in the master branch failed in Oracle GraalVM For JDK 23.ea.13 .

**To Reproduce**

When possible, provide a link to a repository which reproduces the issue, with instructions on how to use.
The reproducer **must** make use of either the Maven or Gradle plugin.

```bash
sdk install java 23.ea.13-graal
sdk use java 23.ea.13-graal

git clone git@github.com:graalvm/native-build-tools.git
cd ./native-build-tools/
git reset --hard fb962b94f9af2cc04f73624d30a6b7c4dfee3768
./gradlew :native-gradle-plugin:functionalTest
```
Please use backticks to [properly format code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).
If possible please attach a complete reproducer here (either as [a zip file](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to public repository/branch).

**Expected behavior**

**Logs**
Add logs to help explain your problem. 
Please use backticks to [properly format big logs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks). 

```bash
$ ./gradlew :native-gradle-plugin:functionalTest
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':settings-plugins:compileKotlin'.
> Unknown Kotlin JVM target: 23

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 13s
<-------------> 0% WAITING
> IDLE
```

**System Info (please complete the following information):**
 - OS: [e.g. `Windows`] `Ubuntu`
 - GraalVM Version [e.g. `22.0 CE`] `Oracle GraalVM`
 - Java Version [e.g. `17`] `23.ea.13`
 - Plugin version [e.g. `native-gradle-plugin:0.9.10`] https://github.com/graalvm/native-build-tools/commit/fb962b94f9af2cc04f73624d30a6b7c4dfee3768

**Additional context**

- Refer to https://github.com/graalvm/native-build-tools/pull/603 .

**Comment by vjovanov** [comment]
Please consider setting the `JAVA_HOME` environment variable to an earlier Java version (e.g., 21 or 17) that will work with kotlin. And also set the `GRAALVM_HOME` to whichever version you need.

Also, have you tried running the project with a non-GraalVM Java 23? I suspect it would fail.

**Comment by linghengqian** [comment]
> Please consider setting the `JAVA_HOME` environment variable to an earlier Java version (e.g., 21 or 17) that will work with kotlin. And also set the `GRAALVM_HOME` to whichever version you need.

- Still looks suspiciously failed. Similar to https://github.com/graalvm/native-build-tools/actions/runs/9517556127/job/26236415815?pr=603 .

> Also, have you tried running the project with a non-GraalVM Java 23? I suspect it would fail.

- I will say that I'm new to kotlin, and I've found that kotlin seems to have never supported jdk23.

**Comment by vjovanov** [comment]
> Still looks suspiciously failed. Similar to https://github.com/graalvm/native-build-tools/actions/runs/9517556127/job/26236415815?pr=603 .

This seems to be a different error message? I could not find `settings-plugins:compileKotlin`. Can we close this issue?

**Comment by linghengqian** [comment]
> > Still looks suspiciously failed. Similar to https://github.com/graalvm/native-build-tools/actions/runs/9517556127/job/26236415815?pr=603 .
> 
> This seems to be a different error message? I could not find `settings-plugins:compileKotlin`. Can we close this issue?

- Yes, I therefore opened #608 to re-expose the error log on Oracle GraalVM For JDK23+.
