### ISSUE TITLE
Links to fortunes.json are still broken

### ISSUE THREAD

**Issue by izeye** [graalvm/native-build-tools#634]
See https://github.com/graalvm/native-build-tools/pull/633#issuecomment-2450021565

**Comment by vjovanov** [comment]
@izeye thanks for being persistent and reporting the issue again!

@olyagpl please have a look, seems we missed a spot.

**Comment by olyagpl** [comment]
@izeye, thanks for sharing the problem.
The fixes are already merged ([maven](https://github.com/graalvm/native-build-tools/blob/master/docs/src/docs/asciidoc/maven-plugin-quickstart.adoc), [gradle](https://github.com/graalvm/native-build-tools/blob/master/docs/src/docs/asciidoc/gradle-plugin-quickstart.adoc)), but the website pages will get refreshed with the next plugins release.

**Comment by izeye** [comment]
@olyagpl They seem to be still referencing ".u8" file, not ".json" file.

See https://github.com/graalvm/native-build-tools/blob/master/docs/src/docs/asciidoc/maven-plugin-quickstart.adoc?plain=1#L135 and https://github.com/graalvm/native-build-tools/blob/master/docs/src/docs/asciidoc/gradle-plugin-quickstart.adoc?plain=1#L118

**Comment by olyagpl** [comment]
As a workaround, you can copy the contents of the file into _fortunes.json_  (with `.json` extension) and it will be fine.
There is an ongoing refactoring of the quick start guides and that will be corrected then. Thank you for pointing!
