### ISSUE TITLE
How to generate 32-bit dll

### ISSUE THREAD

**Issue by wghdir** [graalvm/native-build-tools#643]
Want to write a dll for other programs to call,use --shared to generate dll,but this dll is 64-bit dll,How to generate 32-bit dll?
HelloWorld.java 
import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.type.CCharPointer;
import org.graalvm.nativeimage.c.type.CTypeConversion;

public	class HelloWorld{
	public static void main(String[] args){
		System.out.println("Hello World");
	}
	
	@CEntryPoint(name = "add")
	public static int add(IsolateThread thread, int a, int b) {
    		return a * b;
	}
}
javac HelloWorld.java 
native-image -H:Name=libhelloworld --shared

**Comment by vjovanov** [comment]
This is not supported directly, but the company called [Microdoc](https://www.microdoc.com/) provides this support. CC @koutheir

**Comment by wghdir** [comment]
tks
