### ISSUE TITLE
native-image test execution should be skipped when no test

### ISSUE THREAD

**Issue by dzou** [graalvm/native-build-tools#81]
Currently it looks like if you have a nested project structure in Maven and you define the `native-maven-plugin` in the parent pom, it will run the native build for the empty parent project.

Example project structure ([example](https://github.com/dzou/junit4-experiment)):
```
parent-module/
  child-module/
    pom.xml
  pom.xml
```

If `mvn test -Pnative` is executed from the root, it will still take a few extra minutes to perform an extra native compile for the parent module with no tests in it.

```
[INFO] ====================
[INFO] Initializing project: parent
[INFO] ====================

... does build...

Test run finished after 1 ms
[         1 containers found      ]
[         0 containers skipped    ]
[         1 containers started    ]
[         0 containers aborted    ]
[         1 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

[INFO] ====================
[INFO] Initializing project: child
[INFO] ====================

... does build...

Test run finished after 2 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         2 tests found           ]
[         0 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         0 tests failed          ]
```

I was curious if there is an easy way to skip the native-build for any maven module with no tests defined (if necessary, am open to contributing with some guidance). Or perhaps excluding the run from pom.xml files marked with pom packaging.

**Comment by lazar-mitrovic** [comment]
Yeah I believe this is a bug. It looks like maven plugin assumes that `junit-platform-native` dependency is missing even when configuration is missing due to no tests being present. It also outputs wrong warning:
```
Test configuration file wasn't found. Build will now fallback to test discovery mode.
```
@sdeleuze Any ideas about working around this / potential fix? I'm unsure of the approach we should take in order not to replicate surefire logic, but to be robust as well.

**Comment by sdeleuze** [comment]
Sounds like a bug indeed, native compilation of tests is expected to be skipped when no test. I will check that deeper tomorrow.

**Comment by dzou** [comment]
Thanks for taking a look. Here is a reproducer for convenience: https://github.com/dzou/junit4-experiment

Can be tested with `mvn test -Pnative` from root.
