### ISSUE TITLE
Reorganize this repository as a Gradle project with multiple subprojects

### ISSUE THREAD

**Issue by lazar-mitrovic** [graalvm/native-build-tools#82]
At the moment this repository contains three different projects which are interconnected using bash scripts and `mavenLocal` repository. This (obviously) isn't optimal, and results in duplication of configuration files and complex building logic.

Fixing this issue would provide a top level Gradle project that would host all of the common logic. This would also simplify the CI and streamline the release process.

**Comment by melix** [comment]
@lazar-mitrovic please assign this to me, I'm starting to work on this, so that I can work on the Maven plugin next.
