### ISSUE TITLE
Revamp CI to run tests in parallel.

### ISSUE THREAD

**Issue by lazar-mitrovic** [graalvm/native-build-tools#99]
ATM our gradle workflow takes about 40 minutes to complete. This is approaching the time that it takes to run [GraalVM workflows](https://github.com/oracle/graal/actions). Fix for this would be to run tests using parallel jobs.

**Comment by melix** [comment]
There are multiple ways to do this, but clearly as we add test coverage the situation won't get any better.

**Comment by melix** [comment]
In the options:

- manually create buckets of tests and create different workflow runs for each bucket
- add a task which generates buckets of tests and generates the workflow files
   - this task could scan the test directories to create one workflow per functional test
   - or it could create a hashing strategy to put all tests in a bucket automatically
- or we could use a product like Gradle Enterprise to get test distribution (probably not possible medium term)

**Comment by lazar-mitrovic** [comment]
IMO we should manually create buckets of tests and then run each bucket in a separate parallel job. Note "job" and not a "workflow" since might want to reuse outputs of a job that downloads GraalVM and the one that builds required plugin/feature. 

ATM for each workflow we only use one job with multiple steps, which is semantically oposite to what we are trying to achieve. Steps are always run sequentially - jobs are run in parallel by default (except when there is a depency to another job execution).
